openapi: 3.0.3
info:
  title: Activiti Public Rest About Process Instances Information API
  description: " The Alfresco Activiti BPM Suite comes with a REST API. It includes both an Enterprise equivalent of the Activiti Open Source REST API exposing the generic Activiti Engine operations, and a dedicated set op REST API endpoints specific for the functionality in the Alfresco Activiti BPM Suite. \n      Note that there is also an 'internal' REST API, which are the REST endpoints used by the Javascript UI. It is advised not to use this API, these REST API urls and way of using it will change and evolve with the product and are unsupported. The supported API is stable. Also, the internal REST API uses a different authentication mechanism tailored towards web browser usage.\n"
  version: 1.4.0
  contact:
    name: Activiti Community
    url: https://www.activiti.org/
    email: activiti-community@alfresco.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{host}/activiti-app
  description: Activiti BPM Server
  variables:
    host:
      default: localhost:8080
      description: The Activiti server host
security:
- basicAuth: []
tags:
- name: Process Instances Information
  description: Manage process instances
paths:
  /api/enterprise/process-instances:
    post:
      tags:
      - Process Instances Information
      summary: Start a process instance
      operationId: startNewProcessInstanceUsingPOST
      requestBody:
        description: startRequest
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProcessInstanceRepresentation'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessInstanceRepresentation'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/enterprise/process-instances/{processInstanceId}/field-content:
    get:
      tags:
      - Process Instances Information
      summary: Retrieve content attached to process instance fields
      operationId: getProcessInstanceContentUsingGET
      parameters:
      - name: processInstanceId
        in: path
        description: processInstanceId
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultListDataRepresentation'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    ResultListDataRepresentation:
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/AbstractRepresentation'
        size:
          type: integer
          format: int32
        start:
          type: integer
          format: int32
        total:
          type: integer
          format: int32
    AbstractRepresentation: {}
    CreateProcessInstanceRepresentation:
      properties:
        name:
          type: string
        outcome:
          type: string
        processDefinitionId:
          type: string
        values:
          type: object
    RestVariable:
      properties:
        name:
          type: string
        scope:
          type: string
        type:
          type: string
        value:
          type: object
        valueUrl:
          type: string
    LightUserRepresentation:
      properties:
        email:
          type: string
        externalId:
          type: string
        firstName:
          type: string
        id:
          type: integer
          format: int64
        lastName:
          type: string
        pictureId:
          type: integer
          format: int64
    ProcessInstanceRepresentation:
      properties:
        businessKey:
          type: string
        ended:
          type: string
          format: date-time
        graphicalNotationDefined:
          type: boolean
        id:
          type: string
        name:
          type: string
        processDefinitionCategory:
          type: string
        processDefinitionDeploymentId:
          type: string
        processDefinitionDescription:
          type: string
        processDefinitionId:
          type: string
        processDefinitionKey:
          type: string
        processDefinitionName:
          type: string
        processDefinitionVersion:
          type: integer
          format: int32
        startFormDefined:
          type: boolean
        started:
          type: string
          format: date-time
        startedBy:
          $ref: '#/components/schemas/LightUserRepresentation'
        tenantId:
          type: string
        variables:
          type: array
          items:
            $ref: '#/components/schemas/RestVariable'
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: HTTP Basic Authentication using valid Activiti user credentials
