openapi: 3.0.3
info:
  title: Activiti Public Rest About Apps Runtime API
  description: " The Alfresco Activiti BPM Suite comes with a REST API. It includes both an Enterprise equivalent of the Activiti Open Source REST API exposing the generic Activiti Engine operations, and a dedicated set op REST API endpoints specific for the functionality in the Alfresco Activiti BPM Suite. \n      Note that there is also an 'internal' REST API, which are the REST endpoints used by the Javascript UI. It is advised not to use this API, these REST API urls and way of using it will change and evolve with the product and are unsupported. The supported API is stable. Also, the internal REST API uses a different authentication mechanism tailored towards web browser usage.\n"
  version: 1.4.0
  contact:
    name: Activiti Community
    url: https://www.activiti.org/
    email: activiti-community@alfresco.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{host}/activiti-app
  description: Activiti BPM Server
  variables:
    host:
      default: localhost:8080
      description: The Activiti server host
security:
- basicAuth: []
tags:
- name: Apps Runtime
  description: Manage Runtime Apps
paths:
  /api/enterprise/runtime-app-definitions:
    get:
      tags:
      - Apps Runtime
      summary: List runtime apps
      description: When a user logs in into the Alfresco Activiti BPM Suite, the landing page is displayed containing all the apps that the user is allowed to see and use.
      operationId: getAppDefinitionsUsingGET
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultListDataRepresentation'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
      - Apps Runtime
      summary: Deploy published app
      description: After creating and puclished an app the user can add it to his/her landing page.
      operationId: deployAppDefinitionsUsingPOST
      requestBody:
        description: saveObject
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RuntimeAppDefinitionSaveRepresentation'
        required: true
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    AppDefinitionRepresentation:
      properties:
        defaultAppId:
          type: string
        deploymentId:
          type: string
        description:
          type: string
        icon:
          type: string
        id:
          type: integer
          format: int64
        modelId:
          type: integer
          format: int64
        name:
          type: string
        tenantId:
          type: integer
          format: int64
        theme:
          type: string
    ResultListDataRepresentation:
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/AbstractRepresentation'
        size:
          type: integer
          format: int32
        start:
          type: integer
          format: int32
        total:
          type: integer
          format: int32
    AbstractRepresentation: {}
    RuntimeAppDefinitionSaveRepresentation:
      properties:
        appDefinitions:
          type: array
          items:
            $ref: '#/components/schemas/AppDefinitionRepresentation'
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: HTTP Basic Authentication using valid Activiti user credentials
