openapi: 3.0.3
info:
  title: Activiti Public Rest About Admin Endpoints API
  description: " The Alfresco Activiti BPM Suite comes with a REST API. It includes both an Enterprise equivalent of the Activiti Open Source REST API exposing the generic Activiti Engine operations, and a dedicated set op REST API endpoints specific for the functionality in the Alfresco Activiti BPM Suite. \n      Note that there is also an 'internal' REST API, which are the REST endpoints used by the Javascript UI. It is advised not to use this API, these REST API urls and way of using it will change and evolve with the product and are unsupported. The supported API is stable. Also, the internal REST API uses a different authentication mechanism tailored towards web browser usage.\n"
  version: 1.4.0
  contact:
    name: Activiti Community
    url: https://www.activiti.org/
    email: activiti-community@alfresco.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{host}/activiti-app
  description: Activiti BPM Server
  variables:
    host:
      default: localhost:8080
      description: The Activiti server host
security:
- basicAuth: []
tags:
- name: Admin Endpoints
  description: Manage Endpoints
paths:
  /api/enterprise/admin/basic-auths:
    get:
      tags:
      - Admin Endpoints
      summary: getBasicAuthConfigurations
      operationId: getBasicAuthConfigurationsUsingGET_1
      parameters:
      - name: tenantId
        in: query
        description: tenantId
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EndpointBasicAuthRepresentation'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
      - Admin Endpoints
      summary: createBasicAuthConfiguration
      operationId: createBasicAuthConfigurationUsingPOST_1
      requestBody:
        description: createRepresentation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEndpointBasicAuthRepresentation'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointBasicAuthRepresentation'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/enterprise/admin/basic-auths/{basicAuthId}:
    get:
      tags:
      - Admin Endpoints
      summary: getBasicAuthConfiguration
      operationId: getBasicAuthConfigurationUsingGET_1
      parameters:
      - name: basicAuthId
        in: path
        description: basicAuthId
        required: true
        schema:
          type: integer
          format: int64
      - name: tenantId
        in: query
        description: tenantId
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointBasicAuthRepresentation'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    put:
      tags:
      - Admin Endpoints
      summary: updateBasicAuthConfiguration
      operationId: updateBasicAuthConfigurationUsingPUT_1
      parameters:
      - name: basicAuthId
        in: path
        description: basicAuthId
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: createRepresentation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEndpointBasicAuthRepresentation'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointBasicAuthRepresentation'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
      - Admin Endpoints
      summary: removeBasicAuthonfiguration
      operationId: removeBasicAuthonfigurationUsingDELETE_1
      parameters:
      - name: basicAuthId
        in: path
        description: basicAuthId
        required: true
        schema:
          type: integer
          format: int64
      - name: tenantId
        in: query
        description: tenantId
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /api/enterprise/admin/endpoints:
    get:
      tags:
      - Admin Endpoints
      summary: getEndpointConfigurations
      operationId: getEndpointConfigurationsUsingGET_1
      parameters:
      - name: tenantId
        in: query
        description: tenantId
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EndpointConfigurationRepresentation'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
      - Admin Endpoints
      summary: createEndpointConfiguration
      operationId: createEndpointConfigurationUsingPOST_1
      requestBody:
        description: representation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointConfigurationRepresentation'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointConfigurationRepresentation'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/enterprise/admin/endpoints/{endpointConfigurationId}:
    get:
      tags:
      - Admin Endpoints
      summary: getEndpointConfiguration
      operationId: getEndpointConfigurationUsingGET_1
      parameters:
      - name: endpointConfigurationId
        in: path
        description: endpointConfigurationId
        required: true
        schema:
          type: integer
          format: int64
      - name: tenantId
        in: query
        description: tenantId
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointConfigurationRepresentation'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    put:
      tags:
      - Admin Endpoints
      summary: updateEndpointConfiguration
      operationId: updateEndpointConfigurationUsingPUT_1
      parameters:
      - name: endpointConfigurationId
        in: path
        description: endpointConfigurationId
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: representation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointConfigurationRepresentation'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointConfigurationRepresentation'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
      - Admin Endpoints
      summary: removeEndpointConfiguration
      operationId: removeEndpointConfigurationUsingDELETE_1
      parameters:
      - name: endpointConfigurationId
        in: path
        description: endpointConfigurationId
        required: true
        schema:
          type: integer
          format: int64
      - name: tenantId
        in: query
        description: tenantId
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    EndpointConfigurationRepresentation:
      properties:
        basicAuthId:
          type: integer
          format: int64
        basicAuthName:
          type: string
        host:
          type: string
        id:
          type: integer
          format: int64
        name:
          type: string
        path:
          type: string
        port:
          type: string
        protocol:
          type: string
        requestHeaders:
          type: array
          items:
            $ref: '#/components/schemas/EndpointRequestHeaderRepresentation'
        tenantId:
          type: integer
          format: int64
    CreateEndpointBasicAuthRepresentation:
      properties:
        name:
          type: string
        password:
          type: string
        tenantId:
          type: integer
          format: int64
        username:
          type: string
    EndpointBasicAuthRepresentation:
      properties:
        created:
          type: string
          format: date-time
        id:
          type: integer
          format: int64
        lastUpdated:
          type: string
          format: date-time
        name:
          type: string
        tenantId:
          type: integer
          format: int64
        username:
          type: string
    EndpointRequestHeaderRepresentation:
      properties:
        name:
          type: string
        value:
          type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: HTTP Basic Authentication using valid Activiti user credentials
