openapi: 3.0.3
info:
  title: Activiti Public Rest About Integration Box API
  description: " The Alfresco Activiti BPM Suite comes with a REST API. It includes both an Enterprise equivalent of the Activiti Open Source REST API exposing the generic Activiti Engine operations, and a dedicated set op REST API endpoints specific for the functionality in the Alfresco Activiti BPM Suite. \n      Note that there is also an 'internal' REST API, which are the REST endpoints used by the Javascript UI. It is advised not to use this API, these REST API urls and way of using it will change and evolve with the product and are unsupported. The supported API is stable. Also, the internal REST API uses a different authentication mechanism tailored towards web browser usage.\n"
  version: 1.4.0
  contact:
    name: Activiti Community
    url: https://www.activiti.org/
    email: activiti-community@alfresco.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{host}/activiti-app
  description: Activiti BPM Server
  variables:
    host:
      default: localhost:8080
      description: The Activiti server host
security:
- basicAuth: []
tags:
- name: Integration Box
  description: Manage Box Integration
paths:
  /api/enterprise/integration/box/confirm-auth-request:
    get:
      tags:
      - Integration Box
      summary: Box Authorization
      description: Returns Box Oauth HTML Page
      operationId: confirmAuthorisationUsingGET_1
      parameters:
      - name: code
        in: query
        description: code
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/enterprise/integration/box/files:
    get:
      tags:
      - Integration Box
      summary: List file & folders
      operationId: getFilesUsingGET
      parameters:
      - name: filter
        in: query
        description: filter
        required: false
        schema:
          type: string
      - name: parent
        in: query
        description: parent
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultListDataRepresentation'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/enterprise/integration/box/status:
    get:
      tags:
      - Integration Box
      summary: Retrieve if Box Integration is enabled
      operationId: getBoxPluginStatusUsingGET
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: boolean
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/enterprise/integration/box/{userId}/account:
    get:
      tags:
      - Integration Box
      summary: List Box Account
      operationId: getRepositoryAccountUsingGET
      parameters:
      - name: userId
        in: path
        description: userId
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoxUserAccountCredentialsRepresentation'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
      - Integration Box
      summary: Create Box account
      operationId: createRepositoryAccountUsingPOST
      parameters:
      - name: userId
        in: path
        description: userId
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: credentials
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAccountCredentialsRepresentation'
        required: true
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    put:
      tags:
      - Integration Box
      summary: Update Box account
      operationId: updateRepositoryAccountUsingPUT
      parameters:
      - name: userId
        in: path
        description: userId
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: credentials
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAccountCredentialsRepresentation'
        required: true
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
      - Integration Box
      summary: Delete Box account
      operationId: deleteRepositoryAccountUsingDELETE
      parameters:
      - name: userId
        in: path
        description: userId
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    ResultListDataRepresentation:
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/AbstractRepresentation'
        size:
          type: integer
          format: int32
        start:
          type: integer
          format: int32
        total:
          type: integer
          format: int32
    BoxUserAccountCredentialsRepresentation:
      properties:
        authenticationURL:
          type: string
        expireDate:
          type: string
          format: date-time
        ownerEmail:
          type: string
    UserAccountCredentialsRepresentation:
      properties:
        password:
          type: string
        username:
          type: string
    AbstractRepresentation: {}
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: HTTP Basic Authentication using valid Activiti user credentials
